USE MASTER
GO

IF DB_ID('BIBLIOTECA')IS NOT NULL
BEGIN
 DROP DATABASE BIBLIOTECA
END
GO

CREATE DATABASE BIBLIOTECA

SP_HELPDB BIBLIOTECA
GO

USE BIBLIOTECA 
GO

--Creacion Tabla BIBLIOTECARIO

IF OBJECT_ID('BIBLIOTECARIO') IS NOT NULL
BEGIN  
  DROP TABLE BIBLIOTECARIO
END
GO
CREATE TABLE BIBLIOTECARIO
(
ID_biblio			CHAR(8) NOT NULL,
nombresBiblio		VARCHAR(15) NOT NULL,
apellidosBiblio		VARCHAR(15) NOT NULL,
DNI_Biblio          VARCHAR (10) NOT NULL,
horarioTrabajo		TIME
PRIMARY KEY (ID_biblio)
)
GO

--Creacion tabla USUARIO

IF OBJECT_ID('USUARIO') IS NOT NULL
BEGIN  
  DROP TABLE USUARIO
END
GO
CREATE TABLE USUARIO
(
ID_user              CHAR(8) NOT NULL,
nombreUser           VARCHAR(15) NOT NULL,
apellidoUser         VARCHAR(15) NOT NULL,
direccionUser        VARCHAR(50) NOT NULL,
DNI_User             VARCHAR(10) NOT NULL
PRIMARY KEY (ID_user)
)
GO

--Creacion tabla LIBRO

IF OBJECT_ID('LIBRO') IS NOT NULL
BEGIN  
  DROP TABLE LIBRO
END
GO
CREATE TABLE LIBRO
(
SBN_libro			VARCHAR(15) NOT NULL,
generoLibro			VARCHAR(15) NOT NULL,
editorialLibro		VARCHAR(15) NOT NULL,
tituloLibro         VARCHAR(25) NOT NULL,
num_edicion			VARCHAR (5) NOT NULL,
añoLibro            DATE NOT NULL
PRIMARY KEY (SBN_libro)
)
GO

--Creacion tabla EDITORIAL

IF OBJECT_ID('EDITORIAL') IS NOT NULL
BEGIN  
  DROP TABLE EDITORIAL
END
GO
CREATE TABLE EDITORIAL
(
Ruc_edi				CHAR(15) NOT NULL,   
CatalogoLibro		VARCHAR(100) NOT NULL,
sitioWeb			VARCHAR(40) NOT NULL,
nombreEdi 			VARCHAR(15) NOT NULL
PRIMARY KEY (Ruc_edi)
)
GO

--Creacion tabla BIBLIOTECARIO_TELEFONO

IF OBJECT_ID('BIBLIOTECARIO_TELEFONO') IS NOT NULL
BEGIN  
  DROP TABLE BIBLIOTECARIO_TELEFONO
END
GO
CREATE TABLE BIBLIOTECARIO_TELEFONO
(
ID_biblio			CHAR (8) NOT NULL,  
numCelularBiblio	INT NOT NULL,  
PRIMARY KEY (ID_biblio, numCelularBiblio),
FOREIGN KEY (ID_biblio) REFERENCES BIBLIOTECARIO
)
GO

--Creacion tabla USUARIO_CELULAR

IF OBJECT_ID('USUARIO_CELULAR') IS NOT NULL
BEGIN  
  DROP TABLE USUARIO_CELULAR
END
GO
CREATE TABLE USUARIO_CELULAR
(
ID_user				CHAR(8) NOT NULL,
celularUser			VARCHAR(15) NOT NULL,
PRIMARY KEY (ID_user, celularUser),
FOREIGN KEY (ID_user) REFERENCES USUARIO
)
GO

--Creacion tabla ATENCION

IF OBJECT_ID('ATENCION') IS NOT NULL
BEGIN  
  DROP TABLE ATENCION
END
GO
CREATE TABLE ATENCION
(
ID_biblio			CHAR(8) NOT NULL,
ID_user				CHAR(8) NOT NULL,
PRIMARY KEY (ID_biblio, ID_user),
FOREIGN KEY (ID_biblio) REFERENCES BIBLIOTECARIO,
FOREIGN KEY (ID_user) REFERENCES USUARIO
)
GO

--Creacion tabla PENALIZACION

IF OBJECT_ID('PENALIZACION') IS NOT NULL
BEGIN  
  DROP TABLE PENALIZACION
END
GO
CREATE TABLE PENALIZACION
(
fecha_devolución	DATE NOT NULL,
multa				MONEY NOT NULL,
PRIMARY KEY (fecha_devolución),
)
GO

--Creacion tabla PRESTAMO

IF OBJECT_ID('PRESTAMO') IS NOT NULL
BEGIN  
  DROP TABLE PRESTAMO
END
GO
CREATE TABLE PRESTAMO
(
ID_user				CHAR(8) NOT NULL,
SBN_libro			VARCHAR(15) NOT NULL,
fecha_devolución	DATE NOT NULL,
PRIMARY KEY (ID_user, SBN_libro),
FOREIGN KEY (fecha_devolución) REFERENCES PENALIZACION,
FOREIGN KEY (SBN_libro) REFERENCES LIBRO,
FOREIGN KEY (ID_user) REFERENCES USUARIO
)
GO

--Creacion tabla SBN_AUTOR

IF OBJECT_ID('SBN_AUTOR') IS NOT NULL
BEGIN  
  DROP TABLE SBN_AUTOR
END
GO
CREATE TABLE SBN_AUTOR
(
SBN_libro			VARCHAR(15) NOT NULL,
autorLibro			VARCHAR(30) NOT NULL,
PRIMARY KEY (SBN_libro, autorLibro),
FOREIGN KEY (SBN_libro) REFERENCES LIBRO
)
GO

--Creacion tabla EDITORIAL_LIBRO

IF OBJECT_ID('EDITORIAL_LIBRO') IS NOT NULL
BEGIN  
  DROP TABLE EDITORIAL_LIBRO
END
GO
CREATE TABLE EDITORIAL_LIBRO
(
SBN_libro			VARCHAR(15) NOT NULL,
Ruc_edi				CHAR(15) NOT NULL,
PRIMARY KEY (SBN_libro, Ruc_edi),
FOREIGN KEY (SBN_libro) REFERENCES LIBRO,
FOREIGN KEY (Ruc_edi) REFERENCES EDITORIAL
)
GO


--Creacion tabla EDITORIAL_DIRECCION

IF OBJECT_ID('EDITORIAL_DIRECCION') IS NOT NULL
BEGIN  
  DROP TABLE EDITORIAL_DIRECCION
END
GO
CREATE TABLE EDITORIAL_DIRECCION
(
direccionEdi		VARCHAR(40) NOT NULL,
Ruc_edi				CHAR(15) NOT NULL,
PRIMARY KEY (direccionEdi, Ruc_edi),
FOREIGN KEY (Ruc_edi) REFERENCES EDITORIAL
)
GO

--Creacion tabla EDITORIAL_TELEFONO

IF OBJECT_ID('EDITORIAL_TELEFONO') IS NOT NULL
BEGIN  
  DROP TABLE EDITORIAL_TELEFONO
END
GO
CREATE TABLE EDITORIAL_TELEFONO
(
numContacto			VARCHAR(15) NOT NULL,
Ruc_edi				CHAR(15) NOT NULL,
PRIMARY KEY (numContacto, Ruc_edi),
FOREIGN KEY (Ruc_edi) REFERENCES EDITORIAL
)
GO
